### ISSUE TITLE
更改 memos 导入文件夹时，Flomo Moments.md 显示错误

### ISSUE THREAD

**Issue by Norman-h** [jia6y/flomo-to-obsidian#1]
![image](https://user-images.githubusercontent.com/40519737/215237522-3627ae2a-4097-416e-a95b-96d255ad3f7e.png)
由于此处代码写死，会导致未索引到文件，我的修改在我本地运行良好。

**Comment by jia6y** [comment]
多谢建议。
memo文件夹也修改成可自定义的路径了。
如果您需要修改memo文件夹，您可以
option 1. 重新import，修改tatget memo location
option 2. 直接重命名memo文件夹，obsidian仍然可以从它的索引里定位到文件，然后替换原本的链接。

**Comment by jia6y** [comment]
fix applied, mark the issue as closed for now.
