### ISSUE TITLE
canvas的卡片尺寸太大没法统一调整字体大小和卡片尺寸

### ISSUE THREAD

**Issue by yoghurtdewdew** [jia6y/flomo-to-obsidian#11]
![image](https://github.com/jia6y/flomo-to-obsidian/assets/63794438/a2b91401-fb87-4d69-8391-25d6bf2003c1)

canvas的卡片尺寸太大没法统一调整字体大小和卡片尺寸

**Comment by jia6y** [comment]
感谢，是很好的建议，我在导入时加入了尺寸选择的选项。
<img width="649" alt="image" src="https://github.com/jia6y/flomo-to-obsidian/assets/1456952/7f251873-c0b8-43d1-95ad-15058accf97c">
