### ISSUE TITLE
是否可能将所有的memo直接导入到一个md文件中？

### ISSUE THREAD

**Issue by yoghurtdewdew** [jia6y/flomo-to-obsidian#12]
感觉一条memo一个文件的话，文件蛮多的，是否可能将所有的memo直接导入到一个md文件中，每个memo加一个[[YYYY-MM-DD]]链接到日记，这样应该会比较简洁

**Comment by jia6y** [comment]
多谢反馈！确实考虑过这个，做了一个类似的功能。
“Flomo Moment” 这个文件链接了所有memo文件，并且按照时间先后显示。
<img width="196" alt="image" src="https://github.com/jia6y/flomo-to-obsidian/assets/1456952/f94393c2-262b-45cd-bd55-7a0da13e5de1">

**Comment by yoghurtdewdew** [comment]
感谢回复！我看到所有的文件了，但是我的memo通常都比较短，所以通过preview的形式，一页只能显示几条：
<img width="673" alt="image" src="https://github.com/jia6y/flomo-to-obsidian/assets/63794438/2e425700-918e-492b-a015-01ce240ddee0">

如果可以有方法直接提取文本到正文，就能在一页里浏览更多，所以我还蛮希望是这样的显示形式：

方案一：
一个md文档，按照标题索引的形式（按照日[[YYYY-MM-DD]]，或按周[[YYYY-W27]]、按月份[[YYYY-MM]] 索引）
## memo@[[YYYY-MM-DD]]
- memo1……
- memo2……
## memo@[[YYYY-MM-DD]]
- memo3……
- memo4……

方案二：
一个md文档，无标题索引，直接将日期简短的添加到每个memo的句末
- memo1……[[YYYY-MM-DD]]
- memo2……[[YYYY-MM-DD]]

**Comment by jia6y** [comment]
您的意思是在flomo moment页面里，所有的memo只显示了它的一部分内容，而没有完整把每一个memo显示出来？

**Comment by yoghurtdewdew** [comment]
不是，我的意思是，我的一篇memo比较短，目前在obsidian里通过嵌入的方式，以及一个memo一篇的方式，空白区域太多了，一页只能看到三四个，和在手机上差不多，而我预想的是在电脑上可以屏幕更大，一页能看到很多很多很多篇；另一方面就是觉得比较碎片化，希望能够集中到一起

**Comment by yoghurtdewdew** [comment]
所以我比较希望有一个方式，能够将所有的memo同步到一个md文件上，然后日期通过在内容里带上一定的wiki链接

**Comment by jia6y** [comment]
功能加上了，采用类似方案一的方式
![image](https://github.com/jia6y/flomo-to-obsidian/assets/1456952/33ecb408-95fb-4e72-b4fa-3add9be30ac7)

**Comment by yoghurtdewdew** [comment]
感谢！

我刚更新好插件和试用了下，发现仍然无法实现将所有内容同步到一个页面

比如目前的结果是：

每个date一个文件夹，其实不需要这些文件夹

<img width="250" alt="image" src="https://github.com/jia6y/flomo-to-obsidian/assets/63794438/6639091b-9b3e-4672-9e02-796ab4692188">

日期和时间用代码块来索引，而不是使用标题格式索引

<img width="601" alt="image" src="https://github.com/jia6y/flomo-to-obsidian/assets/63794438/b9e40c4a-45cf-4af4-b942-c7e80c64a436">


为了方便理解，我将我的需求做一个截图并放个文本，可以看看好不好实现？

一种是，用标题来索引，所有内容都在一个页面

<img width="397" alt="image" src="https://github.com/jia6y/flomo-to-obsidian/assets/63794438/a19447e4-333e-4056-bd77-598da3d63df0">
<img width="277" alt="image" src="https://github.com/jia6y/flomo-to-obsidian/assets/63794438/063dd19d-dd2f-4ac1-84c3-7f73009b531f">

一种是，用层级大纲缩进，这种还可以和Logseq兼容

<img width="380" alt="image" src="https://github.com/jia6y/flomo-to-obsidian/assets/63794438/1bd38fab-304a-403e-96bc-665bf956176a">
<img width="326" alt="image" src="https://github.com/jia6y/flomo-to-obsidian/assets/63794438/592c13f5-0c6a-455b-88b0-d2a024c24724">

**Comment by jia6y** [comment]
感谢建议。我可能还是会保留单独的memo文件，尽量不去改变已有的功能和使用方式以免影响其他用户。
我会考虑您提供的索引方式，把memo以索引（按您图所示）显示在一个文件中。memo内容会以全文预览的方式展示出来，显示效果应该和将所有memo直接嵌入到一个文件中显示区别不大。
可能会放到下个release里。

**Comment by yoghurtdewdew** [comment]
感谢您的回复！目前插件能够将每个或每天的memo同步到单独的文件，真的非常棒！

目前保留了memo的单独页面，嵌入到一个md文件中，但嵌入的文件是无法直接进行编辑的，无标题目录索引也使得只能通过鼠标滚轮来回滑动、想看看或比较特定日期范围的内容必须频繁切换页面无法在单个页面中迅速跳转，想要搜索替换一部分内容需要同时在多个文件中搜索毕竟嵌入的文件无法修改，那相当于，成功导入了，但还是不方便后续的浏览和整理。

确实我的习惯不太相同，我在flomo里记录的文字内容甚至可能比标签还短，所以我不太喜欢太多页面。我的需求是，直接将一切memo导出到单个md文件（非一篇一篇的嵌入的方式），通过日期以markdown标题或大纲缩进标记的形式来索引memo，这样得到页面，在第三个级别的内容就是纯正的memo内容，同一天内容的使用同一个日期标题（YYYY-MM-DD）、不同的时间点（HH:mm）开头的文字即可（直接通过标题引用就嵌入了当天的flomo中的内容），通过日期标题及目录可以直观的看到哪些天有/没有记录，通过日期标题之间的行数就能直观的知道某个日期范围内记录的内容多/少。

这对后续的浏览和整理是非常有意义的。
比如，可以在日记/周记录/月记录模板中通过引用单个md页面的日期标题直接嵌入当天的memo内容，甚至一级、二级日期标题可以直接分别使用`[[YYYY-MM]]`、`[[YYYY-MM-DD]]`作为格式就与自己的记录自动关联起来了。
如果是大纲格式索引，还可以在其他大纲app中进一步整理并保留层级关系。
如果是标题格式索引，就能在obsidian通过标题目录里的级别快速跳转到特定日期的memo切能直观的看到内容，而无须切换文件，无须在长长的狭窄的文件和文件夹中来回倒腾。

**Comment by yoghurtdewdew** [comment]
啊 你好强 我不会编程… 以后有机会的话向你请教😂
