### ISSUE TITLE
关于导入后图片链接问题

### ISSUE THREAD

**Issue by Ploter4815** [jia6y/flomo-to-obsidian#13]
如果一条 Memo 下同时有多个图片，导入后图片链接全都处于同一行，跟下面类似：

```markdown
![](xxx/xxxx/xxx1.jpg)![](xxx/xxxx/xxx2.jpg)![](xxx/xxxx/xxx3.jpg)![](xxx/xxxx/xxx4.jpg)
```

我有使用 [Image auto upload](https://github.com/renmu123/obsidian-image-auto-upload-plugin) 来把我的图片全部上传到图床，而这个插件还不支持识别这种格式的链接（只识别出第一张图片），所以不知道老哥能不能改成一行一个链接呢？像这样：

```markdown
![](xxx/xxxx/xxx1.jpg)

![](xxx/xxxx/xxx2.jpg)

![](xxx/xxxx/xxx3.jpg)
```

**Comment by jia6y** [comment]
您好这个问题解决了，过几天会发布出来  😃

**Comment by Ploter4815** [comment]
我查看了您相关的更改，不知道能不能使用两个换行符 `\n` 呢？

这样图片链接与正文直接有个空行，图片链接与图片链接之间也有个空行，看起来会舒服一点🫡

**Comment by jia6y** [comment]
嗯确实只加了一个\n，但其实阅读模式下面不管几个 \n 显示行间空白距离都是一样的。Obsidian会优化MD文档的空行显示。

**Comment by jia6y** [comment]
等我先发布出来咱门先看看效果，需要的话咱门再调整 :)

**Comment by Ploter4815** [comment]
辛苦老哥国庆发版，链接是能成功换行了，但地址用尖括号的话，Ob能正常识别，这个图片自动上传的插件不能正确识别了就。
不知道能否采用原来的地址形式，或者说给一个选项？
![image](https://github.com/jia6y/flomo-to-obsidian/assets/69951143/a15bbbdb-6d49-4e56-b1d2-6429a2e1fbc8)

**Comment by jia6y** [comment]
> 辛苦老哥国庆发版，链接是能成功换行了，但地址用尖括号的话，Ob能正常识别，这个图片自动上传的插件不能正确识别了就。 不知道能否采用原来的地址形式，或者说给一个选项？ ![image](https://user-images.githubusercontent.com/69951143/272313248-a15bbbdb-6d49-4e56-b1d2-6429a2e1fbc8.png)

多谢反馈，刚更新了一个小布丁，应该ok了。
