### ISSUE TITLE
无序列表将 `*` 符号换成 `-` 符号，统一列表缩进。

### ISSUE THREAD

**Issue by KrDw9ec4** [jia6y/flomo-to-obsidian#15]
在 Obsidian 中，如果用 `*` 来做无序列表符号的话，大概率会被误识别成斜体。

希望能将**无序列表符号**改成 `-`，以及希望能**统一空格缩进**为4个空格（Obsidian 默认）。

![image](https://github.com/jia6y/flomo-to-obsidian/assets/142046049/1b38fdfb-9298-494e-b996-e609a3cc6da7)

图一是导入后在 Obsidian 中出现的错误样式；

![image](https://github.com/jia6y/flomo-to-obsidian/assets/142046049/a62e8c40-87d7-44a5-bce4-7fa8364784b7)

图二是导入后的具体文本；

![image](https://github.com/jia6y/flomo-to-obsidian/assets/142046049/50251fa1-878a-4c5c-b130-4268d74f51c7)

图三是（VS Code）具体空格情况。

**Comment by jia6y** [comment]
应该ok了，我换了个md parser，原来的那个有bug

**Comment by KrDw9ec4** [comment]
> 应该ok了，我换了个md parser，原来的那个有bug

不知道是不是这个原因，变化好大😥

- 原本 flomo 中换行后导入到 Obsidian 中会有空行，现在没有了；
- 导入图片后的链接地址中被 `<>` 包裹。

列表我还没试，应该解决了，辛苦老哥国庆发版😘

**Comment by KrDw9ec4** [comment]
抱歉再打扰一下老哥，之前提过统一空格缩进，今晚想起来测试一下，现在空格缩进是统一成4个空格了，但一是会出现**多余的空行**（虽然渲染后正常），二是**列表标识符变成了 `*   `，有三个空格**，如果可以的话还是希望用 `- ` 这样标准的格式，不好实现的话就算了。

这是 flomo 中的内容：

![image](https://github.com/jia6y/flomo-to-obsidian/assets/142046049/02748d5c-cc66-4d73-aca1-0b635a3f0c89)

这是导入后的样式：

![image](https://github.com/jia6y/flomo-to-obsidian/assets/142046049/3c6e1b6f-a472-4105-b805-1cbb3206888f)

**Comment by jia6y** [comment]
- 多余的空行是因为flomo产生列表时候会插入额外的标签，导致markdown converter会插入空行，我试了不同的converter都是一样的行为
- 列表标签已经改好了，重新安装一下就能生效（卸载插件，再安装一次）

**Comment by KrDw9ec4** [comment]
> * 多余的空行是因为flomo产生列表时候会插入额外的标签，导致markdown converter会插入空行，我试了不同的converter都是一样的行为

了解了，那我自己用正则 `^ +$\n` 删除空行吧，这空行还挺好匹配的😁

> * 列表标签已经改好了，重新安装一下就能生效（卸载插件，再安装一次）

重装就好了，感谢老哥🫡

**Comment by sheyoshan** [comment]
> * 多余的空行是因为flomo产生列表时候会插入额外的标签，导致markdown converter会插入空行，我试了不同的converter都是一样的行为
> * 列表标签已经改好了，重新安装一下就能生效（卸载插件，再安装一次）

我發現，在手機應用程式端，紀錄的大綱式筆記，再使用這個插件輸入到Obsidian之後，行列和行列之間不會出現空格。
但是在電腦端紀錄大綱式筆記的話，行列和行列之間就會出現空格。
我的猜想是因為電腦端和手機端，在換行的時候，有硬回車和軟回車的差別。

**Comment by jia6y** [comment]
> > * 多余的空行是因为flomo产生列表时候会插入额外的标签，导致markdown converter会插入空行，我试了不同的converter都是一样的行为
> > * 列表标签已经改好了，重新安装一下就能生效（卸载插件，再安装一次）
> 
> 我發現，在手機應用程式端，紀錄大綱式筆記，再使用這個插件輸入到Obsidian之後，行列和行列之間不會出現空格。 但是在電腦端紀錄大綱式筆記的話，行列和行列之間就會出現空格。 我的猜想是因為電腦端和手機端，在換行的時候，有硬回車和軟回車的差別。

插件在转译md 的时候是会出现这个问题，我也在考虑如何解决。最近比较忙可能没时间更新。

**Comment by sheyoshan** [comment]
> > > * 多余的空行是因为flomo产生列表时候会插入额外的标签，导致markdown converter会插入空行，我试了不同的converter都是一样的行为
> > > * 列表标签已经改好了，重新安装一下就能生效（卸载插件，再安装一次）
> > 
> > 
> > 我發現，在手機應用程式端，紀錄大綱式筆記，再使用這個插件輸入到Obsidian之後，行列和行列之間不會出現空格。 但是在電腦端紀錄大綱式筆記的話，行列和行列之間就會出現空格。 我的猜想是因為電腦端和手機端，在換行的時候，有硬回車和軟回車的差別。
> 
> 插件在转译md 的时候是会出现这个问题，我也在考虑如何解决。最近比较忙可能没时间更新。

謝謝作者，有意思的是，

反倒是因為目前還有這個導出限制，
反過來影響我一開始的筆記工作流習慣，
也就是不再使用flomo來寫大綱式筆記。

要寫大綱式筆記就回到Obsidian中，
使用「Outliner」插件來寫。

另外儘量精簡flomo筆記，所有flomo筆記都不超過一個段落，
儘量讓每一則筆記都原子化。

進行這樣的改變之後，
反而輸出靈感筆記的效率和頻率都變高了。

況且flomo也強調了，
大綱式筆記不是flomo的強項。
可以去選擇Workflowy、幕布。

筆記和工具流，會反過來影響思維模式，
山不轉，路轉；路不轉，人轉。 : D
