### ISSUE TITLE
从flomo导入ob的时候,能否支持 #标签 转化为为 [[标签]]

### ISSUE THREAD

**Issue by weqoocu** [jia6y/flomo-to-obsidian#16]
目前已经使用双链代替了标签. 在flomo上输入标签比输入双链更方便. 输入侧可以这么操作

不过在导入的ob的时候,是否支持将标签都转为双链呢? 这样方便记录的内容,与已有的主题产生链接.

**Comment by musicleaf** [comment]
不知道能支持么

**Comment by musicleaf** [comment]
在么

**Comment by weqoocu** [comment]
继续顶一下

**Comment by sheyoshan** [comment]
> 目前已经使用双链代替了标签. 在flomo上输入标签比输入双链更方便. 输入侧可以这么操作
> 
> 不过在导入的ob的时候,是否支持将标签都转为双链呢? 这样方便记录的内容,与已有的主题产生链接.

weqoocu 你好

我一開始也和你有同樣的問題，後來修改自己筆記工作流來適配插件，請參考：

1. 和筆記「內容」相關的關鍵詞，直接在段落中加入[[雙鏈]]。
2. 和筆記「功能性」相關的內容，在筆記最後加入「標籤」。

範例如下：

這是我在flomo中的一則筆記

- 剛剛發現了一個新的，增加flomo筆記中[[批注]]的方式。原因是因為，在flomo中，筆記是有一個獨一無二的地址的，所以我們在進行批注的時候，需要在新的筆記中加入這個獨一無二的地址，讓新的筆記可以連結過去。問題是：如果這個筆記之後從flomo被導入到Obsidian中，那麼這一層的功能就會消失。所以，為了讓以後我還可以[[順藤摸瓜]]，找到這則筆記的[[脈絡]]，所以如果我在批注筆記的時候，會從舊的筆記中，擷取裡面的一段內容，複製在新的筆記中，這樣的話，這個內容就會成為連結上一篇筆記的索引（當然，如果舊的筆記中有一個類似標題的內容、或是開頭一句話的話，那樣更好。）格式可以是這樣：XXXX/XX/XX我提到了：（上一則筆記的內容、標題）。XXXX/XX/XX批注： #0406筆記/01靈感 #0411流程

和這則筆記中，有高度相關的關鍵詞有：[[批注]]、[[順藤摸瓜]]、[[脈絡]]
這則筆記在我的筆記系統中，是一則靈感筆記、以及一個流程，因此加上：#0406筆記/01靈感 #0411流程 的標籤。
（標籤的編號是採用杜威十進制和PARA的概念制定而成、flomo和Obsidian是使用同一套標籤系統。）

日後，只要我搜尋[[批注]]，就能夠找到和[[批注]]相關的內容。
假如使用 標籤 來標註「內容」的話，日後會導致標籤不斷增加。
但是「功能性」則是不會增加那麼快的。

---

區分內容和功能性 另一個範例：

1. - [[日記]]：日記是一種寫作文體
2. - 今天心情不太好，目前專案進度不太順利。 #日記

1. 代表的是，描述 日記 這個概念的是什麼。所以用雙鏈。2. 代表的是這篇筆記的功能，也就是我的日記。因此使用標籤。

---

另外，由於flomo並沒有內建雙鏈功能，
我們可以使用輸入法制定熱鍵，例如我的熱鍵為「www = [[ 」、「eee = ]]」
就可以實現輸出時，不間斷地插入雙鏈。

請您參考
