### ISSUE TITLE
类似weread插件，通过网页登录获取cookie自动同步

### ISSUE THREAD

**Issue by zhuxining** [jia6y/flomo-to-obsidian#18]
十分感谢这个插件🙏🙏🙏

作者要不要考虑一下类似obsidian-weread-plugin那种弹出网页登录后自动同步的功能

https://github.com/zhaohongxuan/obsidian-weread-plugin

<img width="1093" alt="image" src="https://github.com/jia6y/flomo-to-obsidian/assets/12285468/da1eb671-6b1e-4487-add1-246de57c3c10">

**Comment by zhuxining** [comment]
还有就是这个根据日期自动插入到每日笔记中，这个功能也超实用
<img width="785" alt="image" src="https://github.com/jia6y/flomo-to-obsidian/assets/12285468/817e7e6b-40ae-4fb5-a2b7-e56f9678acca">

**Comment by jia6y** [comment]
好提议！最急有点忙，忙完来看看怎么做😃

**Comment by weqoocu** [comment]
超级期待自动导入功能，目前手动导入操作太麻烦

**Comment by jia6y** [comment]
新版本支持自动同步了，不需要再去手动导出文件了。

**Comment by jia6y** [comment]
自动导出目前需要playwright的依赖。
