### ISSUE TITLE
請求轉譯html語法：<mark>...</mark>

### ISSUE THREAD

**Issue by sheyoshan** [jia6y/flomo-to-obsidian#20]
**1. 說明**

在flomo筆記中，我會使用 螢光筆 工具，
將重要的部分給標註出來。

導出html檔案之後，
content之中的內容會將 螢光筆 標註的部分，
顯示為 < /mark > ... < /mark >。

**2. 請求**

請問是否能添加 
將下列 html 語法 < /mark > ... < /mark >，
轉譯為 markdown 語法 ==...==
的功能？

**3. 目的**

讓導入到Obsidian中的flomo筆記，
也可以顯示 螢光筆 標註的效果。

謝謝您 ：）

**Comment by jia6y** [comment]
好的我会看看如何实现。
荧光笔看起来是新的功能，这个版本的插件发布的时候还没有。
最近比较忙，可能没有那么快更新

**Comment by jia6y** [comment]
已经解决，并且新版本支持自动导入了。

**Comment by jia6y** [comment]
自动导出目前需要playwright的依赖。

**Comment by sheyoshan** [comment]
非常感謝您！

螢光筆和加粗功能，對寫筆記量大的夥伴，非常重要。
我在flomo寫筆記的時候，會手動添加[[...]]雙鏈在關鍵字上，
但在flomo添加==...==則不甚美觀，因此仍想要保有原生螢光效果，
同時又希望可以再導入Obsidian之後，保有螢光筆畫線的訊息。

少楠和Light在《筆記的方法》中也提到，
給筆記內容畫螢光和加粗，也是一個精煉資訊重要的手段，
從flomo導入到Obsidian的過程中，
丟失了螢光筆畫線的資訊，
真的讓人很苦惱...

您的無私協助肯定會造福廣大flomo和Obsidian的使用者！

再次感謝您寶貴的時間、百忙之中更新這個優秀的插件！
