### ISSUE TITLE
自动同步提示错误是什么原因

### ISSUE THREAD

**Issue by weqoocu** [jia6y/flomo-to-obsidian#23]
这是什么意思？

<img width="301" alt="image" src="https://github.com/jia6y/flomo-to-obsidian/assets/35360006/e559e2ad-f51e-400f-82b2-31c459fbd494">

**Comment by jia6y** [comment]
这个问题解决了么？

**Comment by weqoocu** [comment]
解决了



---原始邮件---
发件人: "Jialu ***@***.***&gt;
发送时间: 2024年4月1日(周一) 晚上6:29
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [jia6y/flomo-to-obsidian] 自动同步提示错误是什么原因 (Issue #23)




 
这个问题解决了么？

**Comment by jia6y** [comment]
是安装了playwright吗

**Comment by weqoocu** [comment]
对的，通过终端安装了playwright


在 2024年4月1日 19:04，Jialu ***@***.***> 写道：


是安装了playwright吗

**Comment by jia6y** [comment]
好的，多谢，我去更新一下文档。
然后再看看怎么去掉这个依赖。

**Comment by jia6y** [comment]
有任何进一步的问题，请移步到dicussion里讨论
https://github.com/jia6y/flomo-to-obsidian/discussions
