### ISSUE TITLE
是增量同步么？

### ISSUE THREAD

**Issue by weqoocu** [jia6y/flomo-to-obsidian#24]
每次同步都是全量同步么？ 效率有点低呢

<img width="562" alt="image" src="https://github.com/jia6y/flomo-to-obsidian/assets/35360006/1abcec28-e4bc-4aa6-b530-f488568e1507">

**Comment by jia6y** [comment]
全量，flomo并没有提供api，现在的自动同步也是基于导出文件，和手动导出/导入的量是一样的。

**Comment by weqoocu** [comment]
时候可以记录同步时间，下次就过滤一下时间



---原始邮件---
发件人: "Jialu ***@***.***&gt;
发送时间: 2024年4月1日(周一) 晚上6:31
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [jia6y/flomo-to-obsidian] 是增量同步么？ (Issue #24)




 
全量，flomo并没有提供api，现在的自动同步也是基于导出文件，和手动导出/导入的量是一样的。

**Comment by jia6y** [comment]
如果增量同步的话，不仅要同步新的记录，也要同步更改过的记录。
而且，目前flomo只支持全量导出，目前还没有很好的办法做到增量。

**Comment by weqoocu** [comment]
只更新增量的条目即可



---原始邮件---
发件人: "Jialu ***@***.***&gt;
发送时间: 2024年4月1日(周一) 晚上7:07
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [jia6y/flomo-to-obsidian] 是增量同步么？ (Issue #24)




 
如果增量同步的话，不仅要同步新的记录，也要同步更改过的记录。
 而且，目前flomo只支持全量导出，目前还没有很好的办法做到增量。

**Comment by sheyoshan** [comment]
> 只更新增量的条目即可
> […](#)
> ---原始邮件--- 发件人: "Jialu ***@***.***&gt; 发送时间: 2024年4月1日(周一) 晚上7:07 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [jia6y/flomo-to-obsidian] 是增量同步么？ (Issue #24) 如果增量同步的话，不仅要同步新的记录，也要同步更改过的记录。 而且，目前flomo只支持全量导出，目前还没有很好的办法做到增量。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

作者寫的這個插件在執行上很優秀，
我有3000多則筆記在flomo上，全量導入也不過10秒以內的事情。
如果要進行增量導入的話，手動調整也不難，
只要固定在flomo上選擇匯出指定日期區間，
然後匯入到Obsidian中即可。
