### ISSUE TITLE
chromium版本号似乎是hardcode，期望对应环境中安装的版本

### ISSUE THREAD

**Issue by yuxingwei** [jia6y/flomo-to-obsidian#33]
windows11，执行npx playwright install默认安装最新chromium
![image](https://github.com/jia6y/flomo-to-obsidian/assets/62556743/ce2d5fdc-9db4-4c92-b185-5ee30ce7168c)
但是插件登录使用的却是1112
![image](https://github.com/jia6y/flomo-to-obsidian/assets/62556743/8a99f7ef-0fd3-4cc4-b0c2-968c47675cfe)

目前workaround的方式如下
尝试指定chromium版本下载似乎失败
![image](https://github.com/jia6y/flomo-to-obsidian/assets/62556743/be4bb4fd-acc5-43e2-afb8-b0879cbd0e93)
拷贝1124版本为新副本，重命名chromium-1112，登录和同步成功

**Comment by jia6y** [comment]
我正在解决这个问题

**Comment by yuxingwei** [comment]
卸载环境中的playwright后安装指定版本
npx playwright@1.43.1 install
下载release最新文件到Obsidian登录成功
<img width="594" alt="iShot_2024-08-18_12 52 30" src="https://github.com/user-attachments/assets/d7bc7bbf-7811-4ec7-a60a-92e06a70e7fc">
感谢作者的支持:)
