### ISSUE TITLE
Uncaught Reference Error: ImporterUI is not defined

### ISSUE THREAD

**Issue by forgetpwd** [jia6y/flomo-to-obsidian#34]
after run flomo importer, nothing happened. 
check the console and get following errors:

Uncaught ReferenceError: importerUI is not defined
    at Object.callback (main.ts:44:5)
    at RK (app.js:1:2040412)
    at t.onChooseItem (app.js:1:2630332)
    at t.onChooseSuggestion (app.js:1:1584862)
    at t.selectSuggestion (app.js:1:1584412)
    at e.useSelectedItem (app.js:1:1582271)
    at e.onSuggestionClick (app.js:1:1582007)
    at HTMLDivElement.s (enhance.js:1:10720)

DevTools failed to load source map: Could not load content for app://obsidian.md/main.js.map: System error: net::ERR_FILE_NOT_FOUND

**Comment by jia6y** [comment]
May I confirm the Ob version and Plugin version?
ImporterUI is no longer in use in the current plugin version

**Comment by forgetpwd** [comment]
my ob is v1.6.5 and flomo importer is v1.3.0

**Comment by jia6y** [comment]
not sure if you tried reinstallation, could you have a try?

**Comment by jia6y** [comment]
I mean reinstall the pluggin

**Comment by jia6y** [comment]
In the latest codebase, it's already renamed to "AuthUI" (line #44 in main.ts). So most likely you were using an out-of-date version? Maybe re-install the plugin could help.

<img width="471" alt="image" src="https://github.com/jia6y/flomo-to-obsidian/assets/1456952/4a15b23a-aa64-4892-bc15-d0995195d1de">

**Comment by forgetpwd** [comment]
it is probably due to the incomplete update from obsidian.  i uninstall it and re-install it again and now seems working.
thanks for your help!

**Comment by forgetpwd** [comment]
not sure if this is related. but i still got error when try to use autosync.  

the error message is as below snapshots:
![Snipaste_2024-06-29_23-23-17](https://github.com/jia6y/flomo-to-obsidian/assets/3833022/0bfe653e-c6b2-4baa-8c6a-4de56974222a)


i already run the npx playwright install in cmd line and it shows installation has been done.

**Comment by jia6y** [comment]
Yeah, that's something I am looking into right now.
The precompiled plugin code hardcoded the playwright version, while "npx install" always targets the latest one.

**Comment by jia6y** [comment]
The workaround is renaming the folder to chromium-1112 under AppData.
<img width="335" alt="image" src="https://github.com/jia6y/flomo-to-obsidian/assets/1456952/a62e68df-f05d-439e-9c52-c0bb6e51ff31">

**Comment by forgetpwd** [comment]
your workaround works. thanks again.  you can close the issue.
