### ISSUE TITLE
自动同步时无法登陆flomo

### ISSUE THREAD

**Issue by dennes2020** [jia6y/flomo-to-obsidian#35]
安装的最新版本，playwright最新版本也安装了，从flomo导出zip压缩包在obsidian中导入正常。但是选择自动同步时显示错误，提示Sign-in was failed.
<img width="808" alt="image" src="https://github.com/user-attachments/assets/7744ddd3-2e83-4532-b02a-a5142dced42a">

**Comment by jia6y** [comment]
应为playwright的版本有点问题，我最近准备解决
有个workaround是重命名**chromium**文件夹到c**hromium-1112**

**Comment by jia6y** [comment]
更新了安装命令，需要使用指定版本。因为插件是预编译的，所以比较难实现 playwright库版本的更替。
