### ISSUE TITLE
为什么导入的数量少了？

### ISSUE THREAD

**Issue by musicleaf** [jia6y/flomo-to-obsidian#6]
导入逻辑是呢？ 我2000多个memos，为啥就只导入900多各

**Comment by jia6y** [comment]
您好，因为flomo导出的数据文件有时候会缺失关键的html标签，导致了在parse成markdown的时候会出现错误。这些有缺失标签的memo就无法导入了。
我得看看这些被缺失标签的规律，看看能不能在解析成markdown之前解决。

**Comment by musicleaf** [comment]
好的，期待。

**Comment by musicleaf** [comment]
1.

**Comment by musicleaf** [comment]
好的，期待

**Comment by jia6y** [comment]
![image](https://user-images.githubusercontent.com/1456952/226070653-4bdf826d-54aa-4d7f-b32a-bd8fdd85c6f9.png)

能帮忙确认一下flomo导出memo的数量吗

**Comment by musicleaf** [comment]
<img width="624" alt="image" src="https://user-images.githubusercontent.com/35360006/226074043-24855faa-2bbd-47a8-8f15-4f402d822a7e.png">

**Comment by musicleaf** [comment]
大概知道原因了： flomo有两个两个memo的创建时间是一样的（比如：2022-08-31 08:20:09），导入的数据是按照：memo@2022_08_31_08_20_09来命名，只到秒， 就只能导入一条
<img width="635" alt="image" src="https://user-images.githubusercontent.com/35360006/226074589-61240013-7af3-4399-ab24-e597321b6e6f.png">


<img width="605" alt="image" src="https://user-images.githubusercontent.com/35360006/226074673-f3a14d44-bb96-49d1-a973-1cd6f5fa2d10.png">

**Comment by jia6y** [comment]
好的，了解了

**Comment by jia6y** [comment]
多谢反馈，我修改完回复您

**Comment by musicleaf** [comment]
> 多谢反馈，我修改完回复您

太感谢了，期待，这个工具真的好用

**Comment by jia6y** [comment]
试试吧。命名规则更新了，加上了序号，不会有覆盖了。
您可以尝试导入到一个新的文件夹看看有没有遗失的memo了。
有啥问题随时留言。 :)

**Comment by musicleaf** [comment]
整理没有什么问题了：有部分可能因为标签迁移其他文件夹了。 优秀，感谢


<img width="302" alt="image" src="https://user-images.githubusercontent.com/35360006/227399408-10716626-4ed9-4333-82f5-09b0273407f4.png">


<img width="616" alt="image" src="https://user-images.githubusercontent.com/35360006/227399626-21ae209f-1a76-443a-b01c-dbf6635b9e7e.png">

**Comment by jia6y** [comment]
好的 ，多谢反馈  :)
刚修复了一个小bug，有空跟新一下吧。
