### ISSUE TITLE
希望双链不要被转义。

### ISSUE THREAD

**Issue by musicleaf** [jia6y/flomo-to-obsidian#7]
笔记的双链为啥被转义了：
故意在flomo输入双链，方便导入ob后自动和对应的主题建立连接，比如：
[[搜狗输入法]]使用了输入法的自定义短语功能，可以快速的增加内链，在输入flomo的可以快速的增加一个双链。

---

导入后变成这样，双链失效，期待不要转义

`\[\[搜狗输入法\]\]`使用了输入法的自定义短语功能，可以快速的增加内链，在输入flomo的可以快速的增加一个双链。

**Comment by jia6y** [comment]
在flomo导出的backup文件里双向链是有效的吗，能给我截图看一下吗。
我这边看下来，flomo导出的时候双向链其实就已经和之前不一样了。

**Comment by musicleaf** [comment]
导出内容，看源代码是没有被转义的

<img width="1395" alt="image" src="https://user-images.githubusercontent.com/35360006/230517714-5e3e6343-0b36-48a5-bcc7-e446f565126b.png">

**Comment by musicleaf** [comment]
求优化，嘻嘻：）

**Comment by jia6y** [comment]
您好，这个功能加上了。
请尝试一下新的release，正式发布还得等审批流程 :)
https://github.com/jia6y/flomo-to-obsidian/releases

![image](https://github.com/jia6y/flomo-to-obsidian/assets/1456952/ec875ede-aa92-436e-8f5f-86f401217cb9)

**Comment by jia6y** [comment]
我已经发布了，您可以在插件市场里直接更新了。建议您也把Obsidian更新到最新版。
