### ISSUE TITLE
新需求：导入到obsidian时， 标签能转化为双链，方便后续能快速检索到

### ISSUE THREAD

**Issue by musicleaf** [jia6y/flomo-to-obsidian#8]
如下图，在标签后面增加一个对应的双链：

<img width="409" alt="image" src="https://user-images.githubusercontent.com/35360006/235827507-ee007d96-b39a-4743-a201-c685648377d2.png">

**Comment by jia6y** [comment]
好滴，我来看看怎么处理。最近比较忙。

**Comment by jia6y** [comment]
您好，这个功能暂时可能不考虑实现。谢谢您的意见。:)
