### ISSUE TITLE
需求：增加导入为白板的功能

### ISSUE THREAD

**Issue by Ploter4815** [jia6y/flomo-to-obsidian#9]
**有考虑过导入 memo 到一个白板里吗？**

因为在我的方案中，memo 最后还是不会留在 Obsidian 里的，徒增 Obsidian 库中的笔记量；加之白板特别适合用来整理像是 memos 这样碎片化的记录。
目前的我的操作是导出当天的 memo，通过您的插件导入到 Obsidian 中，然后**拖动文件夹到白板中再进行整理**，这样当然已经能满足我的主要需求了。
我还有一个需求就是留档当天的 memos（当然这可能是不必要的），但由于我的操作相当于在白板中引用导入后的 memo，删除导入的 memo 笔记（留 memo 在库中不好管理）后白板中就不会显示了，遂来提提 issue
如果您考虑开发的话可以参照下 ob 原生的“拖动文件夹到白板”这个操作，这个产生的卡片大小我觉得挺好的
不过貌似现在 Obsidian 并没有提供有关白板的 API（我不了解，只是听说）？

**Comment by jia6y** [comment]
您好，感谢您的意见，这个功能做好了
您可以尝试最新的release，正式发布还需走审批流程。
https://github.com/jia6y/flomo-to-obsidian/releases

![image](https://github.com/jia6y/flomo-to-obsidian/assets/1456952/3a89ab3e-6c6b-49d1-8f72-24d7ea313a6d)

**Comment by jia6y** [comment]
未必和您的描述100%吻合。
我在导入时增加了创建到Canvas的选项。您可以选择“Generate Canvas with content”，这样会将文件内容创建在canvas中。

**Comment by jia6y** [comment]
建议您升级Obsidian到最新版然后尝试Canvas功能。Obsidian在最新版里修复了一些问题。

**Comment by Ploter4815** [comment]
感谢老哥开发，新功能比我想象的要完善，我刚开始发这个issue需要的是“Generate Canvas with content”这个功能，但我这些天实践下来发现“Generate Canvas”这种直接引用笔记适合我😄

**Comment by jia6y** [comment]
:)
